# TakuNet configuration file

# Base Settings
num_epochs: 300
batch_size: 64
seed: 22
experiment_name: GDNet_AIDERV2
main_runs_folder: /home/user/src/runs
pin_memory: False
mode: train

# Logging
tensorboard: True
wandb: False # if True, you need to set the WANDB_API_KEY environment variable

# Dataset and Data loading
num_workers: 12
persistent_workers: True
dataset: AIDERV2
data_path: ./data/AIDERV2
num_classes: 4
img_height: 224
img_width: 224
augment: AIDER
k_folds: 0
split: proportional
no_validation: True

# Pytorch Lightning Precision
lightning_precision: 32-true

# Model settings
network: GDNet
input_channels: 3
dense: True
stem_reduction: 4
ckpts_path: runs/GDNet_AIDERV2/version_40/checkpoints/best_model_val_loss.ckpt

# Optimization parameters
optimizer: rmsprop
scheduler: step # before changing the scheduler, check how it works on the PyTorch documentation
scheduler_per_epoch: True
learning_rate: 0.001
learning_rate_decay: 0.975
learning_rate_decay_steps: 2
min_learning_rate: null
warmup_epochs: 0
warmup_steps: -1
weight_decay: 0.00001
weight_decay_end: 0.00001
update_freq: 1
label_smoothing: 0.0
model_ema: False
alpha: 0.9
momentum: 0.9
class_weights: null

# Export
onnx_opset_version: 17