# TakuNet configuration file

# Base Settings
num_epochs: 300
batch_size: 64
seed: 22
experiment_name: TakuNet_AIDER
main_runs_folder: /home/user/src/runs
pin_memory: False
mode: test

# Logging
tensorboard: True
wandb: False # if True, you need to set the WANDB_API_KEY environment variable

# Dataset and Data loading
num_workers: 0
persistent_workers: False
dataset: AIDER
data_path: /home/user/Data/AIDER
num_classes: 5
img_height: 240
img_width: 240
augment: AIDER
k_folds: 0
split: proportional
no_validation: True

# Pytorch Lightning Precision
lightning_precision: 16-mixed #32-true

# Model settings
network: TakuNet
input_channels: 3
dense: True
stem_reduction: 4
ckpts_path: ckpts/TakuNet_AIDER.ckpt

# Optimization parameters
optimizer: rmsprop
scheduler: step # before changing the scheduler, check how it works on the PyTorch documentation
scheduler_per_epoch: True
learning_rate: 0.001
learning_rate_decay: 0.975
learning_rate_decay_steps: 2
min_learning_rate: null
warmup_epochs: 0
warmup_steps: -1
weight_decay: 0.00001
weight_decay_end: 0.00001
update_freq: 1
label_smoothing: 0.0
model_ema: False
alpha: 0.9
momentum: 0.9
class_weights: null

# Export
onnx_opset_version: 17